### ISSUE TITLE
Adding <b> and <i>

### ISSUE THREAD

**Issue by Crissov** [arve0/markdown-it-underline#1]
I'm considering to use this plugin as a basis for another simple one that distinguishes `<i>` from `<em>` and `<b>` from `<strong>`. Maybe you want to adopt this to, but your precedence would probably differ from my preferred one:

| Markdown | My HTML | Your HTML |
|----|----|----|
| `*` | `<em>` | `<em>` |
| `**` | `<strong>` | `<strong>` |
| `***` | `<strong><em>` | `<strong><em>` |
| `_` | `<i>` | `<u>` |
| `__` | `<b>` | `<i>` |
| `___` | `<b><i>` | `<u><i>` |
| `____` | `<u>` | `<b>` |
| `_____` | `<u><i>` | `<b><u>` |
| `______` | `<u><b>` | `<b><i>` |
| `_______` | `<u><b><i>` | `<b><i><u>` |

**Comment by arve0** [comment]
Hi!
I think that defeats the purpose for this plugin, considering the <i> case.
Also, I believe your cases are out of scope for the name, underline.

You are welcome to use my code as a basis and maintain your own fork. :-)

man. 5. feb. 2018 kl. 01:09 skrev Christoph Päper <notifications@github.com

**Comment by Crissov** [comment]
My fork now exists at <https://github.com/Crissov/markdown-it-emph/>.
